package com.yonyou.cyxdms.framework.bean.entity.base;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.Version;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import com.yonyou.cyx.framework.bean.dto.base.BaseDTO;
import com.yonyou.cyx.framework.bean.entity.base.BasePO;
import com.yonyou.cyx.function.utils.bean.BeanMapperUtil;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * 所有PO 的基类
 *
 * @author renwd
 * @since 2018/7/22 0022
 */
public abstract class DMSBasePO<T extends Model> extends BasePO<T> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dc_change_data_content.CREATED_BY
     *
     * @mbggenerated Wed Jul 18 20:48:49 CST 2018
     */
    @TableField(fill = FieldFill.INSERT)
    private String createdBy;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dc_change_data_content.UPDATED_BY
     *
     * @mbggenerated Wed Jul 18 20:48:49 CST 2018
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private String updatedBy;
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dc_change_data_content.RECORD_VERSION
     *
     * @mbggenerated Wed Jul 18 20:48:49 CST 2018
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    @Version
    private Integer recordVersion;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private Integer isDeleted;

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getRecordVersion() {
        return recordVersion;
    }

    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    protected Serializable pkVal() {
        return null;
    }

    /**
     * 将PO 信息转化为DTO
     *
     * @param dtoClass 需要转化的DTO 信息
     * @return T
     * @author zhangxianchao
     * @since 2018/7/22 0022
     */
    @Override
    protected <T extends BaseDTO> T transDtoToPo(Class<T> dtoClass) {
        return BeanMapperUtil.copyProperties(this, dtoClass);
    }

    /**
     * 将PO 信息转化为DTO
     *
     * @return T
     * @author zhangxianchao
     * @since 2018/7/22 0022
     */
    @Override
    protected <T extends BaseDTO> void transDtoToPo(com.yonyou.cyx.framework.bean.entity.base.BasePO po, T dto) {
        BeanMapperUtil.copyProperties(po, dto);
    }

    /**
     * 定义赋值的抽象方法，以便子类继承并实现此方法
     *
     * @param po
     * @return void
     * @author zhangxianchao
     * @since 2018/10/8 0008
     */
    @Override
    protected <T extends BaseDTO> void populateValueByMethod(T po){}

    /**
     * 定义赋值的抽象方法，以便子类继承并实现此方法
     */
    @Override
    public Map<String,Object> toMaps(){
        return BeanMapperUtil.toMap(this);
    }

}